# # Starter pipeline
# # Start with a minimal pipeline that you can customize to build and deploy your code.
# # Add steps that build, run tests, deploy, and more:
# # https://aka.ms/yaml

# trigger:
# - master

# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'
trigger:
- main  # Trigger pe ramura main (poți să modifici dacă este altă ramură)

pool:
  vmImage: 'ubuntu-latest'  # Folosește o mașină virtuală Ubuntu pentru a construi proiectul
  name: Default  # Asigură-te că acest pool este setat corect

steps:
- task: Maven@3
  displayName: 'Build with Maven'
  inputs:
    mavenPomFile: 'pom.xml'  # Căutăm fișierul pom.xml
    goals: 'clean install'  # Execută comanda clean install pentru a construi proiectul

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'  # Publică artefactele construite
